apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: simple-api
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: dgkanatsios/simpleapp